export const ADMIN_LOGIN_REQUEST ="ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS ="ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED ="ADMIN_LOGIN_FAILED";


export const ADMIN_GET_PROFILE_REQUEST ="ADMIN_GET_PROFILE_REQUEST";
export const ADMIN_GET_PROFILE_SUCCESS ="ADMIN_GET_PROFILE_SUCCESS";
export const ADMIN_GET_PROFILE_FAILED ="ADMIN_GET_PROFILE_FAILED";


export const ADMIN_LOGOUT_REQUEST ="ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS ="ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAILED ="ADMIN_LOGOUT_FAILED";






