export const GET_ALL_BLOGS_REQUEST ="GET_ALL_BLOGS_REQUEST";
export const GET_ALL_BLOGS_SUCCESS ="GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAILED ="GET_ALL_BLOGS_FAILED";

export const WRITE_BLOGS_REQUEST ="WRITE_BLOGS_REQUEST";
export const WRITE_BLOGS_SUCCESS ="WRITE_BLOGS_SUCCESS";
export const WRITE_BLOGS_FAILED ="WRITE_BLOGS_FAILED";


export const GET_BLOG_BY_ID_REQUEST ="DELETE_BLOG_BY_ID_REQUEST";
export const GET_BLOG_BY_ID_SUCCESS ="DELETE_BLOG_BY_ID_SUCCESS";
export const GET_BLOG_BY_ID_FAILED ="DELETE_BLOG_BY_ID_FAILED";


export const DELETE_BLOG_BY_ID_REQUEST ="DELETE_BLOG_BY_ID_REQUEST";
export const DELETE_BLOG_BY_ID_SUCCESS ="DELETE_BLOG_BY_ID_SUCCESS";
export const DELETE_BLOG_BY_ID_FAILED ="DELETE_BLOG_BY_ID_FAILED";