export const GET_ALL_IMAGE_REQUEST ="GET_ALL_IMAGE_REQUEST";
export const GET_ALL_IMAGE_SUCCESS ="GET_ALL_IMAGE_SUCCESS";
export const GET_ALL_IMAGE_FAILED ="GET_ALL_IMAGE_FAILED";

export const UPLOAD_IMAGE_REQUEST ="UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS ="UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILED ="UPLOAD_IMAGE_FAILED";

export const GET_IMAGE_BY_ID_REQUEST ="DELETE_IMAGE_BY_ID_REQUEST";
export const GET_IMAGE_BY_ID_SUCCESS ="DELETE_IMAGE_BY_ID_SUCCESS";
export const GET_IMAGE_BY_ID_FAILED ="DELETE_IMAGE_BY_ID_FAILED";


export const DELETE_IMAGE_BY_ID_REQUEST ="DELETE_IMAGE_BY_ID_REQUEST";
export const DELETE_IMAGE_BY_ID_SUCCESS ="DELETE_IMAGE_BY_ID_SUCCESS";
export const DELETE_IMAGE_BY_ID_FAILED ="DELETE_IMAGE_BY_ID_FAILED";